name: CS-CoreLib
version: ${project.version}
authors: [mrCookieSlime, John000708, AlexLander123, SoSeDiK]
website: http://thebusybiscuit.github.io/

main: me.mrCookieSlime.CSCoreLibPlugin.CSCoreLib

api-version: 1.13

commands:
  cs_triggerinterface:
    description: Отладочная команда
    usage: Не используйте её
